<a href="https://colab.research.google.com/github/hardeck/data-science-bootcamp/blob/main/chapter1/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello Colab")

Hello Colab


In [1]:
import numpy as np
np.__version__

'1.21.6'

In [16]:
A = np.array([[1,2,3],[1,2,3],[1,1,1]])
B = np.array([[2,2,2],[2,2,2],[0,0,0]])
print(A)
print(B)

[[1 2 3]
 [1 2 3]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [0 0 0]]


In [15]:
A @ B

array([[6, 6, 6],
       [6, 6, 6],
       [4, 4, 4]])

In [30]:
C = np.arange(1,21)
C = C.reshape(4,5)
print(C)
C[:,1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 2,  7, 12, 17])

In [39]:
C.ravel(order="A")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
C.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [47]:
D = np.arange(1,10,0.5)
D
D[D > 5]
D[np.bitwise_not(D > 2)]

array([1. , 1.5, 2. ])

In [50]:
D[np.bitwise_xor(D>2, D<10)]

array([1. , 1.5, 2. ])

In [5]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__